@echo off
REM ============================================
REM Piel Lighthouse Resort - One-Tap Setup Script
REM ============================================

setlocal enabledelayedexpansion

REM Change to the script's directory
cd /d "%~dp0"

echo.
echo 🏝️  Piel Lighthouse Resort - Setup
echo ===================================
echo.

REM Step 1: Check for pnpm
echo [1/6] Checking for pnpm...
where pnpm >nul 2>&1
if %errorlevel% equ 0 (
    for /f "delims=" %%i in ('pnpm --version') do set pnpmVersion=%%i
    echo    ✓ pnpm version %pnpmVersion% found
    echo.
) else (
    echo    ✗ pnpm not found. Please install pnpm first:
    echo      npm install -g pnpm
    echo.
    pause
    exit /b 1
)

REM Step 2: Install dependencies
echo [2/6] Installing dependencies with pnpm...
call pnpm install
if %errorlevel% equ 0 (
    echo    ✓ Dependencies installed successfully
    echo.
) else (
    echo    ✗ Failed to install dependencies
    echo.
    pause
    exit /b 1
)

REM Step 3: Create environment file with auto-generated secrets
echo [3/6] Setting up environment variables...
if exist ".env.local" (
    echo    ⚠ .env.local already exists, skipping...
    echo.
) else (
    if exist ".env.local.example" (
        echo    Creating .env.local with auto-generated secrets...
        echo. > .env.local
        (
            echo # ============================================
            echo # Piel Lighthouse Resort - Environment Variables
            echo # Auto-generated by setup.bat
            echo # ============================================
            echo.
        ) > .env.local

        (
            echo # ============================================
            echo # MongoDB Connection String
            echo # ============================================
            echo MONGODB_URI=mongodb://localhost:27017/piel_lighthouse_resort
            echo.
            echo # ============================================
            echo # Gmail SMTP Configuration
            echo # ============================================
            echo GMAIL_EMAIL=trixtech011@gmail.com
            echo GMAIL_APP_PASSWORD=your-app-password-here
            echo.
            echo # ============================================
            echo # Demo Mode (true = no real emails sent)
            echo # ============================================
            echo DEMO_MODE=true
            echo.
            echo # ============================================
            echo # Application Settings
            echo # ============================================
            echo NEXT_PUBLIC_APP_URL=http://localhost:3000
            echo NODE_ENV=development
            echo.
        ) >> .env.local

        REM Generate random secrets using PowerShell
        echo    Generating random secrets...
        for /f "delims=" %%s in ('powershell -Command "[Convert]::ToBase64String([Security.Cryptography.RandomNumberGenerator]::GetBytes(32))"') do set ADMIN_SECRET=%%s
        for /f "delims=" %%s in ('powershell -Command "[Convert]::ToBase64String([Security.Cryptography.RandomNumberGenerator]::GetBytes(32))"') do set STAFF_SECRET=%%s
        for /f "delims=" %%s in ('powershell -Command "[Convert]::ToBase64String([Security.Cryptography.RandomNumberGenerator]::GetBytes(32))"') do set GUEST_SECRET=%%s

        (
            echo # ============================================
            echo # Admin Authentication
            echo # ============================================
            echo ADMIN_SECRET=%ADMIN_SECRET%
            echo ADMIN_USERNAME=admin
            echo ADMIN_PASSWORD_HASH=65e8460c7c9e3c8b9a2e4d1f6c8b3a5e2d4c8b3a5e2d4c8b3a5e2d4c8b3a5e2d4
            echo.
            echo # ============================================
            echo # Staff Portal Settings
            echo # ============================================
            echo STAFF_SECRET=%STAFF_SECRET%
            echo.
            echo # ============================================
            echo # Guest Portal Settings
            echo # ============================================
            echo GUEST_SECRET=%GUEST_SECRET%
            echo.
        ) >> .env.local

        echo    ✓ Created .env.local with auto-generated secrets
        echo.
    ) else (
        echo    ✗ .env.local.example not found
        echo.
        pause
        exit /b 1
    )
)

REM Step 4: Verify TypeScript configuration
echo [4/6] Verifying TypeScript configuration...
call npx tsc --noEmit >nul 2>&1
if %errorlevel% equ 0 (
    echo    ✓ TypeScript configuration is valid
    echo.
) else (
    echo    ⚠ TypeScript check found issues (this may be normal during initial setup)
    echo.
)

REM Step 5: Build the project
echo [5/6] Building the project...
call pnpm run build
if %errorlevel% equ 0 (
    echo    ✓ Build completed successfully
    echo.
) else (
    echo    ✗ Build failed
    echo.
    pause
    exit /b 1
)

REM Step 6: Summary and start option
echo [6/6] Setup Complete!
echo ===================================
echo.
echo 📋 Setup Summary:
echo    ✓ pnpm installed
echo    ✓ Dependencies installed
echo    ✓ Environment file created
echo    ✓ TypeScript verified
echo    ✓ Build completed
echo.
echo ℹ  Default login credentials:
echo    Admin: admin / admin123
echo.
echo ⚠  IMPORTANT: Edit .env.local and add your:
echo    - MongoDB URI (local or Atlas)
echo    - Gmail App Password (if not using demo mode)
echo.
echo ===================================
echo.

REM Ask user if they want to start the dev server
set /p startServer="🚀 Start development server now? (y/n): "
if /i "!startServer!"=="y" (
    echo.
    echo Starting development server...
    echo Press Ctrl+C to stop
    echo.
    pnpm run dev
) else (
    echo.
    echo To start later, run: pnpm run dev
    echo Open http://localhost:3000 in your browser
    echo.
)

endlocal
